version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-app
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  postgres:
    image: postgres:16-alpine
    container_name: plata-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: